---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(maps)

<<<<<<< HEAD
=======

>>>>>>> 750c833024ed367b62c3e7f858bd3833ebd5e4d8
liquor <- read_csv("data/story-sales/Iowa_Liquor_Sales-Story.csv")
```

Separate the lat/long data:

```{r}
liquor <- liquor %>%
  mutate(coord.data = str_extract(`Store Location`, "\\(.*\\)"),
         lat = str_extract(coord.data, "\\(.*,"),
         lon = str_extract(coord.data, ",.*\\)")) %>%
  mutate(lat = str_extract(lat, "[0-9\\.-]{1,}"),
         lon = str_extract(lon, "[0-9\\.-]{1,}")) %>%
  mutate(lat = as.numeric(lat),
         lon = as.numeric(lon),
         `Category Name` = str_to_lower(`Category Name`, locale = "en"),
         category.type = case_when(
           str_detect(`Category Name`, "whisk") ~ "whiskey",
           str_detect(`Category Name`, "vodka") ~ "vodka",
           str_detect(`Category Name`, "rum") ~ "rum",
           str_detect(`Category Name`, "brand") ~ "brandy",
           TRUE ~ "other"
         ))
```

County had both "Story" and "STORY"
```{r}
liquor <- liquor %>%
  mutate(county = "Story")
```

Story county map so that we can plot the lat/long of all of Story county.
```{r}
county <- map("county","iowa.story")
```

```{r}
<<<<<<< HEAD
countyMap <- data.frame(lat=county$y,long=county$x) %>% na.omit()
=======
countyMap <- data.frame(lat=county$x,long=county$y) %>% na.omit()
>>>>>>> 750c833024ed367b62c3e7f858bd3833ebd5e4d8
write_csv(countyMap,path = "data/storyCountyMap.csv",col_names = TRUE)
countyMap %>%
  na.omit() %>%
  ggplot(aes(x=long,y=lat)) +
  geom_path()

liquor %>%
  ggplot(aes(x = lon, y = lat))+
  geom_point()
<<<<<<< HEAD
=======

>>>>>>> 750c833024ed367b62c3e7f858bd3833ebd5e4d8
```

